import { LanguageItemProfileSkillsI } from 'src/app/interfaces/LanguageI';

export const data: LanguageItemProfileSkillsI[] = [
  {
    name: 'angular',
    key: 'angular',
    title: 'Angular',
    icon: 'fab fa-angular',
  },
  {
    name: 'sass',
    key: 'sass',
    title: 'SASS',
    icon: 'fab fa-sass',
  },
  {
    name: 'react',
    key: 'react',
    title: 'React JS',
    icon: 'fab fa-react',
  },
  {
    name: 'wordpress',
    key: 'wordpress',
    title: 'Wordpress',
    icon: 'fab fa-wordpress',
  },
  {
    name: 'android',
    key: 'android',
    title: 'Android',
    icon: 'fab fa-android',
  },
  {
    name: 'app_store_ios',
    key: 'app_store',
    title: 'App Store',
    icon: 'fab fa-app-store-ios',
  },
  {
    name: 'apple',
    key: 'apple',
    title: 'Apple',
    icon: 'fab fa-apple',
  },
  {
    name: 'bitbucket',
    key: 'bitbucket',
    title: 'Bitbucket',
    icon: 'fab fa-bitbucket',
  },
  {
    name: 'android',
    key: 'android',
    title: 'Android',
    icon: 'fab fa-android',
  },
  {
    name: 'bootstrap',
    key: 'bootstrap',
    title: 'Bootstrap',
    icon: 'fab fa-bootstrap',
  },
  {
    name: 'chrome',
    key: 'chrome',
    title: 'Chrome',
    icon: 'fab fa-chrome',
  },
  {
    name: 'firefox',
    key: 'firefox',
    title: 'Firefox',
    icon: 'fab fa-firefox',
  },
  {
    name: 'css3',
    key: 'css3',
    title: 'CSS3',
    icon: 'fab fa-css3',
  },
  {
    name: 'figma',
    key: 'figma',
    title: 'Figma',
    icon: 'fab fa-figma',
  },
  {
    name: 'fort-awesome',
    key: 'fort_awesome',
    title: 'Fort Awesome',
    icon: 'fab fa-fort-awesome',
  },
  {
    name: 'git',
    key: 'git',
    title: 'Git',
    icon: 'fab fa-git',
  },
  {
    name: 'gitlab',
    key: 'gitlab',
    title: 'GitLab',
    icon: 'fab fa-gitlab',
  },
  {
    name: 'google-drive',
    key: 'google_drive',
    title: 'Google Drive',
    icon: 'fab fa-google-drive',
  },
  {
    name: 'html5',
    key: 'html5',
    title: 'HTML5',
    icon: 'fab fa-html5',
  },
  {
    name: 'javascrip',
    key: 'javascript',
    title: 'JavaScript',
    icon: 'fab fa-js',
  },
  {
    name: 'jsfiddle',
    key: 'jsfiddle',
    title: 'JS Fiddle',
    icon: 'fab fa-jsfiddle',
  },
  {
    name: 'laravel',
    key: 'laravel',
    title: 'Laravel',
    icon: 'fab fa-laravel',
  },
  {
    name: 'less',
    key: 'less',
    title: 'LESS',
    icon: 'fab fa-less',
  },
  {
    name: 'linux',
    key: 'linux',
    title: 'Linux',
    icon: 'fab fa-linux',
  },
  {
    name: 'markdown',
    key: 'markdown',
    title: 'MarkDown',
    icon: 'fab fa-markdown',
  },
  {
    name: 'microsoft',
    key: 'microsoft',
    title: 'Microsoft',
    icon: 'fab fa-microsoft',
  },
  {
    name: 'node',
    key: 'node',
    title: 'Node JS',
    icon: 'fab fa-node-js',
  },
  {
    name: 'npm',
    key: 'npm',
    title: 'NPM',
    icon: 'fab fa-npm',
  },
  {
    name: 'php',
    key: 'php',
    title: 'PHP',
    icon: 'fab fa-php',
  },
  {
    name: 'python',
    key: 'python',
    title: 'Python',
    icon: 'fab fa-python',
  },
  {
    name: 'readme',
    key: 'readme',
    title: 'README',
    icon: 'fab fa-readme',
  },
  {
    name: 'safari',
    key: 'safari',
    title: 'Safari',
    icon: 'fab fa-safari',
  },
  {
    name: 'shopify',
    key: 'shopify',
    title: 'Shopify',
    icon: 'fab fa-shopify',
  },
  {
    name: 'sketch',
    key: 'sketch',
    title: 'Sketch',
    icon: 'fab fa-sketch',
  },
  {
    name: 'slack',
    key: 'slack',
    title: 'Slack',
    icon: 'fab fa-slack',
  },
  {
    name: 'ubuntu',
    key: 'ubuntu',
    title: 'Ubuntu',
    icon: 'fab fa-ubuntu',
  },
  {
    name: 'unity',
    key: 'unity',
    title: 'Unity',
    icon: 'fab fa-unity',
  },
  {
    name: 'vuejs',
    key: 'vuejs',
    title: 'Vue JS',
    icon: 'fab fa-vuejs',
  },
  {
    name: 'yarn',
    key: 'yarn',
    title: 'Yarn',
    icon: 'fab fa-yarn',
  },
  {
    name: 'slack',
    key: 'slack',
    title: 'Slack',
    icon: 'fab fa-slack',
  },
];
