import { LanguageItemProfileSkillsI } from 'src/app/interfaces/LanguageI';

export const data: LanguageItemProfileSkillsI[] = [
  {
    name: 'angular',
    key: 'angular',
    title: 'Angular',
    icon: 'fab fa-angular',
    main: true,
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#e23237',
      main: '#e23237',
      secondary: '#c11b20',
      nav_item_edge: '#c11b20',
      btn_mobile: '#c11b20',
      profile_b: '#c11b20',
      logo_fill: '#e23237',
      logo_stroke: '#b52e31',
      logo_scale: '#b52e31',
      fondo: 'none',
    },
  },
  {
    name: 'sass',
    key: 'sass',
    title: 'SASS',
    icon: 'fab fa-sass',
    main: true,
    years: 5,
    percentage: 90,
    colors: {
      current_main: '#cf649a',
      main: '#bc3a7b',
      secondary: '#cf3476',
      nav_item_edge: '#bc3a7b',
      btn_mobile: '#bc3a7b',
      profile_b: '#bc3a7b',
      logo_fill: '#cf649a',
      logo_stroke: '#bc3a7b',
      logo_scale: '#cf3476',
      terciary: '#bc3a7b',
      fondo: 'none',
    },
  },
  {
    name: 'react',
    key: 'react',
    title: 'React JS',
    icon: 'fab fa-react',
    main: true,
    years: 2,
    percentage: 50,
    colors: {
      current_main: '#1cc6f5',
      main: '#0096d2',
      secondary: '#09a6d1',
      nav_item_edge: '#09a6d1',
      btn_mobile: '#0096d2',
      profile_b: '#0096d2',
      logo_fill: '#0096d2',
      logo_stroke: '#0096d2',
      logo_scale: '#09a6d1',
      terciary: '#09a6d1',
      fondo: 'none',
    },
  },
  {
    name: 'wordpress',
    key: 'wordpress',
    title: 'Wordpress',
    icon: 'fab fa-wordpress',
    main: true,
    years: 5,
    percentage: 75,
    colors: {
      current_main: '#444',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'android',
    key: 'android',
    title: 'Android',
    icon: 'fab fa-android',
    main: true,
    years: 1,
    percentage: 40,
    colors: {
      current_main: '#3dc980',
      fondo: 'none',
    },
  },
  {
    name: 'app_store_ios',
    key: 'app_store',
    title: 'App Store',
    icon: 'fab fa-app-store-ios',
    years: 2,
    percentage: 50,
    colors: {
      current_main: '#1c7ff4',
      main: '#0a65d0',
      secondary: '#0071bc',
      nav_item_edge: '#0071bc',
      btn_mobile: '#0a65d0',
      profile_b: '#0a65d0',
      logo_fill: '#0a65d0',
      logo_stroke: '#0a65d0',
      logo_scale: '#0071bc',
      terciary: '#0071bc',
      fondo: 'none',
    },
  },
  {
    name: 'apple',
    key: 'apple',
    title: 'Apple',
    icon: 'fab fa-apple',
    years: 2,
    percentage: 65,
    colors: {
      current_main: '#333',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'bitbucket',
    key: 'bitbucket',
    title: 'Bitbucket',
    icon: 'fab fa-bitbucket',
    years: 5,
    percentage: 90,
    colors: {
      current_main: '#0747a6',
      main: '#063985',
      secondary: '#094293',
      nav_item_edge: '#063985',
      btn_mobile: '#063985',
      profile_b: '#063985',
      logo_fill: '#063985',
      logo_stroke: '#063985',
      logo_scale: '#0061a9',
      terciary: '#094293',
      fondo: 'none',
    },
  },
  {
    name: 'bootstrap',
    key: 'bootstrap',
    title: 'Bootstrap',
    icon: 'fab fa-bootstrap',
    main: true,
    years: 5,
    percentage: 95,
    colors: {
      current_main: '#533b78',
      main: '#422f60',
      secondary: '#6c4675',
      nav_item_edge: '#422f60',
      btn_mobile: '#422f60',
      profile_b: '#422f60',
      logo_fill: '#422f60',
      logo_stroke: '#422f60',
      logo_scale: '#572364',
      terciary: '#6c4675',
      fondo: 'none',
    },
  },
  {
    name: 'github',
    key: 'github',
    title: 'GitHub',
    icon: 'fab fa-github',
    main: true,
    years: 7,
    percentage: 85,
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'chrome',
    key: 'chrome',
    title: 'Chrome',
    icon: 'fab fa-chrome',
    years: 10,
    percentage: 95,
    colors: {
      current_main: '#df9e28',
      main: '#b7801b',
      secondary: '#e4a010',
      nav_item_edge: '#b7801b',
      btn_mobile: '#b7801b',
      profile_b: '#b7801b',
      logo_fill: '#b7801b',
      logo_stroke: '#b7801b',
      logo_scale: '#dc9d00',
      terciary: '#e4a010',
      fondo: 'none',
    },
  },
  {
    name: 'firefox',
    key: 'firefox',
    title: 'Firefox',
    icon: 'fab fa-firefox',
    years: 4,
    percentage: 80,
    colors: {
      current_main: '#e96228',
      main: '#c64a14',
      secondary: '#e25f23',
      nav_item_edge: '#c64a14',
      btn_mobile: '#c64a14',
      profile_b: '#c64a14',
      logo_fill: '#c64a14',
      logo_stroke: '#c64a14',
      logo_scale: '#f44611',
      terciary: '#e25f23',
      fondo: 'none',
    },
  },
  {
    name: 'css3',
    key: 'css3',
    title: 'CSS3',
    icon: 'fab fa-css3',
    main: true,
    years: 5,
    percentage: 95,
    colors: {
      current_main: '#2c8ebb',
      main: '#237296',
      secondary: '#0096d2',
      nav_item_edge: '#0a497b',
      btn_mobile: '#237296',
      profile_b: '#237296',
      logo_fill: '#237296',
      logo_stroke: '#237296',
      logo_scale: '#0a497b',
      terciary: '#0096d2',
      fondo: 'none',
    },
  },
  {
    name: 'figma',
    key: 'figma',
    title: 'Figma',
    icon: 'fab fa-figma',
    years: 1,
    percentage: 35,
    colors: {
      current_main: '#1cc6f5',
      main: '#0096d2',
      secondary: '#09a6d1',
      nav_item_edge: '#09a6d1',
      btn_mobile: '#0096d2',
      profile_b: '#0096d2',
      logo_fill: '#0096d2',
      logo_stroke: '#0096d2',
      logo_scale: '#09a6d1',
      terciary: '#09a6d1',
      fondo: 'none',
    },
  },
  {
    name: 'fort-awesome',
    key: 'fort_awesome',
    title: 'Fort Awesome',
    icon: 'fab fa-fort-awesome',
    years: 5,
    percentage: 85,
    colors: {
      current_main: '#333',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'git',
    key: 'git',
    title: 'Git',
    icon: 'fab fa-git-alt',
    main: true,
    years: 5,
    percentage: 80,
    colors: {
      current_main: '#d74a34',
      main: '#b23623',
      secondary: '#d95030',
      nav_item_edge: '#e55137',
      btn_mobile: '#b23623',
      profile_b: '#b23623',
      logo_fill: '#b23623',
      logo_stroke: '#b23623',
      logo_scale: '#e55137',
      terciary: '#d95030',
      fondo: 'none',
    },
  },
  {
    name: 'gitlab',
    key: 'gitlab',
    title: 'GitLab',
    icon: 'fab fa-gitlab',
    years: 5,
    percentage: 80,
    colors: {
      current_main: '#f46a25',
      main: '#c64a14',
      secondary: '#e25f23',
      nav_item_edge: '#c64a14',
      btn_mobile: '#c64a14',
      profile_b: '#c64a14',
      logo_fill: '#c64a14',
      logo_stroke: '#c64a14',
      logo_scale: '#f44611',
      terciary: '#e25f23',
      fondo: 'none',
    },
  },
  {
    name: 'google-drive',
    key: 'google_drive',
    title: 'Google Drive',
    icon: 'fab fa-google-drive',
    years: 8,
    percentage: 50,
    colors: {
      current_main: '#19a464',
      fondo: 'none',
    },
  },
  {
    name: 'html5',
    key: 'html5',
    title: 'HTML5',
    icon: 'fab fa-html5',
    main: true,
    years: 5,
    percentage: 90,
    colors: {
      current_main: '#e96228',
      main: '#c64a14',
      secondary: '#e25f23',
      nav_item_edge: '#c64a14',
      btn_mobile: '#c64a14',
      profile_b: '#c64a14',
      logo_fill: '#c64a14',
      logo_stroke: '#c64a14',
      logo_scale: '#f44611',
      terciary: '#e25f23',
      fondo: 'none',
    },
  },
  {
    name: 'javascript',
    key: 'javascript',
    title: 'JavaScript',
    icon: 'fab fa-js',
    main: true,
    years: 6,
    percentage: 95,
    colors: {
      current_main: '#df9e28',
      main: '#b7801b',
      secondary: '#e4a010',
      nav_item_edge: '#b7801b',
      btn_mobile: '#b7801b',
      profile_b: '#b7801b',
      logo_fill: '#b7801b',
      logo_stroke: '#b7801b',
      logo_scale: '#dc9d00',
      terciary: '#e4a010',
      fondo: 'none',
    },
  },
  {
    name: 'jsfiddle',
    key: 'jsfiddle',
    title: 'JS Fiddle',
    icon: 'fab fa-jsfiddle',
    years: 1,
    percentage: 50,
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'laravel',
    key: 'laravel',
    title: 'Laravel',
    icon: 'fab fa-laravel',
    main: true,
    years: 1,
    percentage: 45,
    colors: {
      current_main: '#eb4d43',
      main: '#da2317',
      secondary: '#f54021',
      nav_item_edge: '#f54021',
      btn_mobile: '#da2317',
      profile_b: '#da2317',
      logo_fill: '#da2317',
      logo_stroke: '#da2317',
      logo_scale: '#f54021',
      terciary: '#f54021',
      fondo: 'none',
    },
  },
  {
    name: 'less',
    key: 'less',
    title: 'LESS',
    icon: 'fab fa-less',
    years: 2,
    percentage: 90,
    colors: {
      current_main: '#0747a6',
      main: '#063985',
      secondary: '#094293',
      nav_item_edge: '#063985',
      btn_mobile: '#063985',
      profile_b: '#063985',
      logo_fill: '#063985',
      logo_stroke: '#063985',
      logo_scale: '#0061a9',
      terciary: '#094293',
      fondo: 'none',
    },
  },
  {
    name: 'linux',
    key: 'linux',
    title: 'Linux',
    icon: 'fab fa-linux',
    main: true,
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'markdown',
    key: 'markdown',
    title: 'MarkDown',
    icon: 'fab fa-markdown',
    years: 3,
    percentage: 70,
    colors: {
      current_main: '#444',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'microsoft',
    key: 'microsoft',
    title: 'Microsoft',
    icon: 'fab fa-microsoft',
    years: 10,
    percentage: 90,
    colors: {
      current_main: '#7cb605',
      main: '#639204',
      secondary: '#57a639',
      nav_item_edge: '#00bb2d',
      btn_mobile: '#639204',
      profile_b: '#639204',
      logo_fill: '#639204',
      logo_stroke: '#639204',
      logo_scale: '#00bb2d',
      terciary: '#57a639',
      fondo: 'none',
    },
  },
  {
    name: 'node',
    key: 'node',
    title: 'Node JS',
    icon: 'fab fa-node-js',
    main: true,
    years: 6,
    percentage: 65,
    colors: {
      current_main: '#7fc728',
      main: '#639204',
      secondary: '#57a639',
      nav_item_edge: '#00bb2d',
      btn_mobile: '#639204',
      profile_b: '#639204',
      logo_fill: '#639204',
      logo_stroke: '#639204',
      logo_scale: '#00bb2d',
      terciary: '#57a639',
      fondo: 'none',
    },
  },
  {
    name: 'npm',
    key: 'npm',
    title: 'NPM',
    icon: 'fab fa-npm',
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#ca3e3d',
      main: '#a52e2d',
      secondary: '#e51d2e',
      nav_item_edge: '#a52e2d',
      btn_mobile: '#a52e2d',
      profile_b: '#a52e2d',
      logo_fill: '#a52e2d',
      logo_stroke: '#a52e2d',
      logo_scale: '#cb3234',
      terciary: '#e51d2e',
      fondo: 'none',
    },
  },
  {
    name: 'php',
    key: 'php',
    title: 'PHP',
    icon: 'fab fa-php',
    main: true,
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#7377ad',
      main: '#555991',
      secondary: '#7f69a5',
      nav_item_edge: '#555991',
      btn_mobile: '#555991',
      profile_b: '#555991',
      logo_fill: '#555991',
      logo_stroke: '#555991',
      logo_scale: '#6576b4',
      terciary: '#7f69a5',
      fondo: 'none',
    },
  },
  {
    name: 'python',
    key: 'python',
    title: 'Python',
    icon: 'fab fa-python',
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#df9e28',
      main: '#b7801b',
      secondary: '#e4a010',
      nav_item_edge: '#b7801b',
      btn_mobile: '#b7801b',
      profile_b: '#b7801b',
      logo_fill: '#b7801b',
      logo_stroke: '#b7801b',
      logo_scale: '#dc9d00',
      terciary: '#e4a010',
      fondo: 'none',
    },
  },
  {
    name: 'readme',
    key: 'readme',
    title: 'README',
    icon: 'fab fa-readme',
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#333',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'safari',
    key: 'safari',
    title: 'Safari',
    icon: 'fab fa-safari',
    years: 2,
    percentage: 50,
    colors: {
      current_main: '#0747a6',
      main: '#063985',
      secondary: '#094293',
      nav_item_edge: '#063985',
      btn_mobile: '#063985',
      profile_b: '#063985',
      logo_fill: '#063985',
      logo_stroke: '#063985',
      logo_scale: '#0061a9',
      terciary: '#094293',
      fondo: 'none',
    },
  },
  {
    name: 'shopify',
    key: 'shopify',
    title: 'Shopify',
    icon: 'fab fa-shopify',
    main: true,
    years: 1,
    percentage: 70,
    colors: {
      current_main: '#91b946',
      main: '#749438',
      secondary: '#bfbf6c',
      nav_item_edge: '#749438',
      btn_mobile: '#749438',
      profile_b: '#749438',
      logo_fill: '#749438',
      logo_stroke: '#749438',
      logo_scale: '#bfbf6c',
      terciary: '#bfbf6c',
      fondo: 'none',
    },
  },
  {
    name: 'sketch',
    key: 'sketch',
    title: 'Sketch',
    icon: 'fab fa-sketch',
    years: 1,
    percentage: 60,
    colors: {
      current_main: '#f5a600',
      main: '#b7801b',
      secondary: '#e4a010',
      nav_item_edge: '#b7801b',
      btn_mobile: '#b7801b',
      profile_b: '#b7801b',
      logo_fill: '#b7801b',
      logo_stroke: '#b7801b',
      logo_scale: '#dc9d00',
      terciary: '#e4a010',
      fondo: 'none',
    },
  },
  {
    name: 'slack',
    key: 'slack',
    title: 'Slack',
    icon: 'fab fa-slack',
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#501650',
      main: '#401240',
      secondary: '#4c2882',
      nav_item_edge: '#630b57',
      btn_mobile: '#401240',
      profile_b: '#401240',
      logo_fill: '#401240',
      logo_stroke: '#401240',
      logo_scale: '#630b57',
      terciary: '#4c2882',
      fondo: 'none',
    },
  },
  {
    name: 'ubuntu',
    key: 'ubuntu',
    title: 'Ubuntu',
    icon: 'fab fa-ubuntu',
    years: 5,
    percentage: 70,
    colors: {
      current_main: '#ec7020',
      main: '#c64a14',
      secondary: '#e25f23',
      nav_item_edge: '#c64a14',
      btn_mobile: '#c64a14',
      profile_b: '#c64a14',
      logo_fill: '#c64a14',
      logo_stroke: '#c64a14',
      logo_scale: '#f44611',
      terciary: '#e25f23',
      fondo: 'none',
    },
  },
  {
    name: 'unity',
    key: 'unity',
    title: 'Unity',
    icon: 'fab fa-unity',
    years: 2,
    percentage: 50,
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'vuejs',
    key: 'vuejs',
    title: 'Vue JS',
    icon: 'fab fa-vuejs',
    years: 1,
    percentage: 50,
    main: true,
    colors: {
      current_main: '#33475b',
      main: '#293949',
      secondary: '#434750',
      nav_item_edge: '#0a497b',
      btn_mobile: '#293949',
      profile_b: '#293949',
      logo_fill: '#293949',
      logo_stroke: '#293949',
      logo_scale: '#0a497b',
      terciary: '#434750',
      fondo: 'none',
    },
  },
  {
    name: 'yarn',
    key: 'yarn',
    title: 'Yarn',
    icon: 'fab fa-yarn',
    years: 2,
    percentage: 70,
    colors: {
      current_main: '#2c8ebb',
      main: '#237296',
      secondary: '#0096d2',
      nav_item_edge: '#0a497b',
      btn_mobile: '#237296',
      profile_b: '#237296',
      logo_fill: '#237296',
      logo_stroke: '#237296',
      logo_scale: '#0a497b',
      terciary: '#0096d2',
      fondo: 'none',
    },
  },
];
