import { LanguageItemProfileSkillsI } from 'src/app/interfaces/LanguageI';

export const data: LanguageItemProfileSkillsI[] = [
  {
    name: 'angular',
    key: 'angular',
    title: 'Angular',
    icon: 'fab fa-angular',
    main: true,
    years: 5,
    percentage: 70,
  },
  {
    name: 'sass',
    key: 'sass',
    title: 'SASS',
    icon: 'fab fa-sass',
    main: true,
    years: 5,
    percentage: 90,
  },
  {
    name: 'react',
    key: 'react',
    title: 'React JS',
    icon: 'fab fa-react',
    main: true,
    years: 2,
    percentage: 50,
  },
  {
    name: 'wordpress',
    key: 'wordpress',
    title: 'Wordpress',
    icon: 'fab fa-wordpress',
    main: true,
    years: 5,
    percentage: 75,
  },
  {
    name: 'android',
    key: 'android',
    title: 'Android',
    icon: 'fab fa-android',
    main: true,
    years: 1,
    percentage: 40,
  },
  {
    name: 'app_store_ios',
    key: 'app_store',
    title: 'App Store',
    icon: 'fab fa-app-store-ios',
    years: 2,
    percentage: 50,
  },
  {
    name: 'apple',
    key: 'apple',
    title: 'Apple',
    icon: 'fab fa-apple',
    years: 2,
    percentage: 65,
  },
  {
    name: 'bitbucket',
    key: 'bitbucket',
    title: 'Bitbucket',
    icon: 'fab fa-bitbucket',
    years: 5,
    percentage: 90,
  },
  {
    name: 'bootstrap',
    key: 'bootstrap',
    title: 'Bootstrap',
    icon: 'fab fa-bootstrap',
    main: true,
    years: 5,
    percentage: 95,
  },
  {
    name: 'github',
    key: 'hithub',
    title: 'GitHub',
    icon: 'fab fa-github',
    main: true,
    years: 7,
    percentage: 85,
  },
  {
    name: 'chrome',
    key: 'chrome',
    title: 'Chrome',
    icon: 'fab fa-chrome',
    years: 10,
    percentage: 95,
  },
  {
    name: 'firefox',
    key: 'firefox',
    title: 'Firefox',
    icon: 'fab fa-firefox',
    years: 4,
    percentage: 80,
  },
  {
    name: 'css3',
    key: 'css3',
    title: 'CSS3',
    icon: 'fab fa-css3',
    main: true,
    years: 5,
    percentage: 95,
  },
  {
    name: 'figma',
    key: 'figma',
    title: 'Figma',
    icon: 'fab fa-figma',
    years: 1,
    percentage: 35,
  },
  {
    name: 'fort-awesome',
    key: 'fort_awesome',
    title: 'Fort Awesome',
    icon: 'fab fa-fort-awesome',
    years: 5,
    percentage: 85,
  },
  {
    name: 'git',
    key: 'git',
    title: 'Git',
    icon: 'fab fa-git-alt',
    main: true,
    years: 5,
    percentage: 80,
  },
  {
    name: 'gitlab',
    key: 'gitlab',
    title: 'GitLab',
    icon: 'fab fa-gitlab',
    years: 5,
    percentage: 80,
  },
  {
    name: 'google-drive',
    key: 'google_drive',
    title: 'Google Drive',
    icon: 'fab fa-google-drive',
    years: 8,
    percentage: 50,
  },
  {
    name: 'html5',
    key: 'html5',
    title: 'HTML5',
    icon: 'fab fa-html5',
    main: true,
    years: 5,
    percentage: 90,
  },
  {
    name: 'javascript',
    key: 'javascript',
    title: 'JavaScript',
    icon: 'fab fa-js',
    main: true,
    years: 6,
    percentage: 95,
  },
  {
    name: 'jsfiddle',
    key: 'jsfiddle',
    title: 'JS Fiddle',
    icon: 'fab fa-jsfiddle',
    years: 1,
    percentage: 50,
  },
  {
    name: 'laravel',
    key: 'laravel',
    title: 'Laravel',
    icon: 'fab fa-laravel',
    main: true,
    years: 1,
    percentage: 45,
  },
  {
    name: 'less',
    key: 'less',
    title: 'LESS',
    icon: 'fab fa-less',
    years: 2,
    percentage: 90,
  },
  {
    name: 'linux',
    key: 'linux',
    title: 'Linux',
    icon: 'fab fa-linux',
    main: true,
    years: 5,
    percentage: 70,
  },
  {
    name: 'markdown',
    key: 'markdown',
    title: 'MarkDown',
    icon: 'fab fa-markdown',
    years: 3,
    percentage: 70,
  },
  {
    name: 'microsoft',
    key: 'microsoft',
    title: 'Microsoft',
    icon: 'fab fa-microsoft',
    years: 10,
    percentage: 90,
  },
  {
    name: 'node',
    key: 'node',
    title: 'Node JS',
    icon: 'fab fa-node-js',
    main: true,
    years: 6,
    percentage: 65,
  },
  {
    name: 'npm',
    key: 'npm',
    title: 'NPM',
    icon: 'fab fa-npm',
    years: 5,
    percentage: 70,
  },
  {
    name: 'php',
    key: 'php',
    title: 'PHP',
    icon: 'fab fa-php',
    main: true,
    years: 5,
    percentage: 70,
  },
  {
    name: 'python',
    key: 'python',
    title: 'Python',
    icon: 'fab fa-python',
    years: 5,
    percentage: 70,
  },
  {
    name: 'readme',
    key: 'readme',
    title: 'README',
    icon: 'fab fa-readme',
    years: 5,
    percentage: 70,
  },
  {
    name: 'safari',
    key: 'safari',
    title: 'Safari',
    icon: 'fab fa-safari',
    years: 2,
    percentage: 50,
  },
  {
    name: 'shopify',
    key: 'shopify',
    title: 'Shopify',
    icon: 'fab fa-shopify',
    main: true,
    years: 1,
    percentage: 70,
  },
  {
    name: 'sketch',
    key: 'sketch',
    title: 'Sketch',
    icon: 'fab fa-sketch',
    years: 1,
    percentage: 60,
  },
  {
    name: 'slack',
    key: 'slack',
    title: 'Slack',
    icon: 'fab fa-slack',
    years: 5,
    percentage: 70,
  },
  {
    name: 'ubuntu',
    key: 'ubuntu',
    title: 'Ubuntu',
    icon: 'fab fa-ubuntu',
    years: 5,
    percentage: 70,
  },
  {
    name: 'unity',
    key: 'unity',
    title: 'Unity',
    icon: 'fab fa-unity',
    years: 2,
    percentage: 50,
  },
  {
    name: 'vuejs',
    key: 'vuejs',
    title: 'Vue JS',
    icon: 'fab fa-vuejs',
    years: 1,
    percentage: 50,
    main: true
  },
  {
    name: 'yarn',
    key: 'yarn',
    title: 'Yarn',
    icon: 'fab fa-yarn',
    years: 2,
    percentage: 70,
  },
];
