import { ProjectI } from '../projects/dataProjects';

export const dataCollaborations: ProjectI[] = [
  {
    name: 'Football Field 3D',
    url: 'http://gofinanzas.com/',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Atom Loader',
    url: 'http://codepen.io/dmsanchez86/full/WxRovR',
    preview: true,
    code: true,
  },
  {
    name: 'Form Perspective',
    url: 'http://codepen.io/dmsanchez86/full/dXqJLv',
    preview: true,
    code: true,
  },
  {
    name: 'Juris Quiz Animation Logo',
    url: 'http://codepen.io/dmsanchez86/full/yJPAqK',
    preview: true,
    code: true,
  },
  {
    name: 'Quotes Machine',
    url: 'http://codepen.io/dmsanchez86/full/xVXjYW',
    preview: true,
    code: true,
  },
  {
    name: 'Ball Loader',
    url: 'http://codepen.io/dmsanchez86/full/OXjROz',
    preview: true,
    code: true,
  },
  {
    name: 'Weather App',
    url: 'http://codepen.io/dmsanchez86/full/bpYXPN/',
    preview: true,
    code: true,
  },
  {
    name: 'Perspective Slide',
    url: 'Perspective_Slider',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Interactive Clock',
    url: 'interactive_clock',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Cellphone 3D',
    url: 'cellphone-3d',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Cube 3D',
    url: 'Cube-3D---CSS3-and-JavaScript',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Lists in 3D',
    url: 'list_in_3d',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Geometry Cube 3D',
    url: 'cube_3D',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Juris Quiz Web',
    url: 'jurisquizWeb',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Arthritis Web',
    url: 'ArthritisWeb',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Basic Angular Template',
    url: 'siema',
    preview: true,
    code: true,
    download: true,
  },
  {
    name: 'Mecaut',
    url: 'https://github.com/dmsanchez86/Mecaut',
    preview: false,
    code: true,
    download: true,
  },
];
