import { ProjectItemI } from 'src/app/interfaces/ProjectItemI';

export const dataPortafolio: ProjectItemI[] = [
  {
    name: 'Krika Cosmetics',
    url: 'http://krikacosmetics.com',
    preview: true,
    key: 'krika',
    type: 'portafolio',
    colors: {
      current_main: '#cf649a',
      main: '#bc3a7b',
      secondary: '#cf3476',
      nav_item_edge: '#bc3a7b',
      btn_mobile: '#bc3a7b',
      profile_b: '#bc3a7b',
      logo_fill: '#bc3a7b',
      logo_stroke: '#bc3a7b',
      logo_scale: '#cf3476',
      terciary: '#bc3a7b',
      fondo: 'none',
    },
  },
  {
    name: 'Librería Nacional',
    url: 'http://librerianacional.com/',
    preview: true,
    key: 'libreria_nacional',
    type: 'portafolio',
    colors: {
      current_main: '#e23237',
      main: '#e23237',
      secondary: '#c11b20',
      nav_item_edge: '#c11b20',
      btn_mobile: '#c11b20',
      profile_b: '#c11b20',
      logo_fill: '#b52e31',
      logo_stroke: '#b52e31',
      logo_scale: '#b52e31',
      fondo: 'none',
    },
  },
  {
    name: 'Energiteca',
    url: 'http://energiteca.com/',
    preview: true,
    key: 'energiteca',
    type: 'portafolio',
    colors: {
      current_main: '#df9e28',
      main: '#b7801b',
      secondary: '#e4a010',
      nav_item_edge: '#b7801b',
      btn_mobile: '#b7801b',
      profile_b: '#b7801b',
      logo_fill: '#b7801b',
      logo_stroke: '#b7801b',
      logo_scale: '#dc9d00',
      terciary: '#e4a010',
      fondo: 'none',
    },
  },
  {
    name: 'AseoYa',
    url: 'http://aseoya.com/',
    preview: true,
    key: 'aseoya',
    type: 'portafolio',
    colors: {
      current_main: '#0747a6',
      main: '#063985',
      secondary: '#094293',
      nav_item_edge: '#063985',
      btn_mobile: '#063985',
      profile_b: '#063985',
      logo_fill: '#063985',
      logo_stroke: '#063985',
      logo_scale: '#0061a9',
      terciary: '#094293',
      fondo: 'none',
    },
  },
  {
    name: 'Existaya',
    url: 'http://existaya.com/',
    preview: true,
    key: 'existaya',
    type: 'portafolio',
    colors: {
      current_main: '#eb4d43',
      main: '#da2317',
      secondary: '#f54021',
      nav_item_edge: '#f54021',
      btn_mobile: '#da2317',
      profile_b: '#da2317',
      logo_fill: '#da2317',
      logo_stroke: '#da2317',
      logo_scale: '#f54021',
      terciary: '#f54021',
      fondo: 'none',
    },
  },
  {
    name: 'STP Networks',
    url: 'http://stpnetworks.com.co/',
    preview: true,
    key: 'stp',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'Coomeva MP',
    url: 'http://coomeva.medicina-prepagada.com/',
    preview: true,
    key: 'coomeva_mp',
    type: 'portafolio',
    colors: {
      current_main: '#7377ad',
      main: '#555991',
      secondary: '#7f69a5',
      nav_item_edge: '#555991',
      btn_mobile: '#555991',
      profile_b: '#555991',
      logo_fill: '#555991',
      logo_stroke: '#555991',
      logo_scale: '#6576b4',
      terciary: '#7f69a5',
      fondo: 'none',
    },
  },
  {
    name: 'Coomeva SAO',
    url: 'https://cuidamostusonrisa.co',
    preview: true,
    key: 'coomeva_sao',
    type: 'portafolio',
    colors: {
      current_main: '#91b946',
      main: '#749438',
      secondary: '#bfbf6c',
      nav_item_edge: '#749438',
      btn_mobile: '#749438',
      profile_b: '#749438',
      logo_fill: '#749438',
      logo_stroke: '#749438',
      logo_scale: '#bfbf6c',
      terciary: '#bfbf6c',
      fondo: 'none',
    },
  },
  {
    name: 'Coomeva Protegete',
    url: 'https://teprotegemos.coomeva.com.co/',
    preview: true,
    key: 'coomeva_pro',
    type: 'portafolio',
    colors: {
      current_main: '#ec7020',
      main: '#c64a14',
      secondary: '#e25f23',
      nav_item_edge: '#c64a14',
      btn_mobile: '#c64a14',
      profile_b: '#c64a14',
      logo_fill: '#c64a14',
      logo_stroke: '#c64a14',
      logo_scale: '#f44611',
      terciary: '#e25f23',
      fondo: 'none',
    },
  },
  {
    name: 'Libreria Nacional App',
    url_play_store:
      'https://play.google.com/store/apps/details?id=com.existaya.librerianacional&hl=es_419',
    preview: true,
    url_app_store:
      'https://apps.apple.com/co/app/librer%C3%ADa-nacional/id1480707806',
    key: 'libreria_nacional_app',
    type: 'portafolio',
    app: true,
    colors: {
      current_main: '#e23237',
      main: '#e23237',
      secondary: '#c11b20',
      nav_item_edge: '#c11b20',
      btn_mobile: '#c11b20',
      profile_b: '#c11b20',
      logo_fill: '#b52e31',
      logo_stroke: '#b52e31',
      logo_scale: '#b52e31',
      fondo: 'none',
    },
  },
  {
    name: 'Energiteca App',
    url_play_store:
      'https://play.google.com/store/apps/details?id=com.existaya.cxapp&hl=en_US',
    url_app_store: 'https://apps.apple.com/gb/app/energiteca/id1441881799',
    preview: true,
    key: 'energiteca_app',
    type: 'portafolio',
    app: true,
    colors: {
      current_main: '#df9e28',
      main: '#b7801b',
      secondary: '#e4a010',
      nav_item_edge: '#b7801b',
      btn_mobile: '#b7801b',
      profile_b: '#b7801b',
      logo_fill: '#b7801b',
      logo_stroke: '#b7801b',
      logo_scale: '#dc9d00',
      terciary: '#e4a010',
      fondo: 'none',
    },
  },
  {
    name: 'AseoYa App',
    url_play_store:
      'https://play.google.com/store/apps/details?id=com.aseoya.app&hl=es_UY',
    url_app_store: 'https://apps.apple.com/co/app/aseoya/id1322485369',
    preview: true,
    key: 'aseoya_app',
    type: 'portafolio',
    app: true,
    colors: {
      current_main: '#0747a6',
      main: '#063985',
      secondary: '#094293',
      nav_item_edge: '#063985',
      btn_mobile: '#063985',
      profile_b: '#063985',
      logo_fill: '#063985',
      logo_stroke: '#063985',
      logo_scale: '#0061a9',
      terciary: '#094293',
      fondo: 'none',
    },
  },
  {
    name: 'GO finanzas',
    url: 'http://gofinanzas.com/',
    preview: true,
    key: 'go',
    type: 'portafolio',
    colors: {
      current_main: '#7cb605',
      main: '#639204',
      secondary: '#57a639',
      nav_item_edge: '#00bb2d',
      btn_mobile: '#639204',
      profile_b: '#639204',
      logo_fill: '#639204',
      logo_stroke: '#639204',
      logo_scale: '#00bb2d',
      terciary: '#57a639',
      fondo: 'none',
    },
  },
  {
    name: 'Entre Pinos',
    url: 'http://entrepinoshostal.com/',
    preview: true,
    key: 'between_pines',
    type: 'portafolio',
    colors: {
      current_main: '#7cb605',
      main: '#639204',
      secondary: '#57a639',
      nav_item_edge: '#00bb2d',
      btn_mobile: '#639204',
      profile_b: '#639204',
      logo_fill: '#639204',
      logo_stroke: '#639204',
      logo_scale: '#00bb2d',
      terciary: '#57a639',
      fondo: 'none',
    },
  },
  {
    name: 'Oral Center',
    url: 'http://oralcenter.com.co/',
    preview: true,
    key: 'oral_center',
    type: 'portafolio',
    colors: {
      current_main: '#0747a6',
      main: '#063985',
      secondary: '#094293',
      nav_item_edge: '#063985',
      btn_mobile: '#063985',
      profile_b: '#063985',
      logo_fill: '#063985',
      logo_stroke: '#063985',
      logo_scale: '#0061a9',
      terciary: '#094293',
      fondo: 'none',
    },
  },
  {
    name: 'Conexiones',
    url: 'http://conexiones.net.co/',
    preview: true,
    key: 'conexiones',
    type: 'portafolio',
    colors: {
      current_main: '#2c8ebb',
      main: '#237296',
      secondary: '#0096d2',
      nav_item_edge: '#0a497b',
      btn_mobile: '#237296',
      profile_b: '#237296',
      logo_fill: '#237296',
      logo_stroke: '#237296',
      logo_scale: '#0a497b',
      terciary: '#0096d2',
      fondo: 'none',
    },
  },
  {
    name: 'Zeus Consultores',
    url: 'http://zeusconsultores.com/',
    preview: true,
    key: 'zeus_web',
    type: 'portafolio',
    colors: {
      current_main: '#0747a6',
      main: '#063985',
      secondary: '#094293',
      nav_item_edge: '#063985',
      btn_mobile: '#063985',
      profile_b: '#063985',
      logo_fill: '#063985',
      logo_stroke: '#063985',
      logo_scale: '#0061a9',
      terciary: '#094293',
      fondo: 'none',
    },
  },
  {
    name: 'I.E Santo Domingo Savio',
    url: 'http://www.iesantodomingosavio.edu.co/',
    preview: true,
    key: 'santodomingo',
    type: 'portafolio',
    colors: {
      current_main: '#7cb605',
      main: '#639204',
      secondary: '#57a639',
      nav_item_edge: '#00bb2d',
      btn_mobile: '#639204',
      profile_b: '#639204',
      logo_fill: '#639204',
      logo_stroke: '#639204',
      logo_scale: '#00bb2d',
      terciary: '#57a639',
      fondo: 'none',
    },
  },
  {
    name: 'Antorcha Films',
    url: 'http://atarrayaitinerante.org/ebookapp/index.html',
    preview: true,
    key: 'antorcha',
    type: 'portafolio',
    colors: {
      current_main: '#eb4d43',
      main: '#da2317',
      secondary: '#f54021',
      nav_item_edge: '#f54021',
      btn_mobile: '#da2317',
      profile_b: '#da2317',
      logo_fill: '#da2317',
      logo_stroke: '#da2317',
      logo_scale: '#f54021',
      terciary: '#f54021',
      fondo: 'none',
    },
  },
  {
    name: 'Rakin.org',
    url: 'http://rakin.org/',
    preview: true,
    key: 'raking',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'JurisQuiz',
    url_play_store:
      'https://play.google.com/store/apps/details?id=com.zopp.jurisquiz',
    app: true,
    key: 'jurisquiz',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'Therapy Tips for',
    url_play_store:
      'https://play.google.com/store/apps/details?id=com.zopp.artritis',
    app: true,
    key: 'therapy',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'Zopp Agency',
    url: 'http://zoppagency.com',
    preview: true,
    key: 'zopp',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'Buffalo Republic',
    url: 'http://buffalorepublic.menu',
    preview: true,
    key: 'buffalo',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'EasyNet',
    url: 'http://easynet.com.co',
    preview: true,
    key: 'easynet',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'CliniWeb',
    url: 'http://cliniweb.co',
    preview: true,
    key: 'cliniweb',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'Clinica de Artritis',
    url: 'http://clinicadeartritistemprana.com/',
    preview: true,
    key: 'hospital',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
  {
    name: 'Finca y Café',
    url: 'http://fincaycafe.com',
    preview: true,
    key: 'finca',
    type: 'portafolio',
    colors: {
      current_main: '#222',
      main: '#111',
      secondary: '#333',
      nav_item_edge: '#222',
      btn_mobile: '#111',
      profile_b: '#111',
      logo_fill: '#111',
      logo_stroke: '#111',
      logo_scale: '#222',
      terciary: '#333',
      fondo: 'none',
    },
  },
];
