import { ProjectItemI } from 'src/app/interfaces/ProjectItemI';

export const dataProjects: ProjectItemI[] = [
  {
    name: 'Football Field 3D',
    url: 'http://dmsanchez86.github.io/Field_3d',
    preview: true,
    code: true,
    download: true,
    key: 'football',
  },
  {
    name: 'Atom Loader',
    url: 'http://codepen.io/dmsanchez86/full/WxRovR',
    preview: true,
    code: true,
    key: 'atom',
  },
  {
    name: 'Form Perspective',
    url: 'http://codepen.io/dmsanchez86/full/dXqJLv',
    preview: true,
    code: true,
    key: 'form',
  },
  {
    name: 'Juris Quiz Animation Logo',
    url: 'http://codepen.io/dmsanchez86/full/yJPAqK',
    preview: true,
    code: true,
    key: 'jurisquiz_app',
  },
  {
    name: 'Quotes Machine',
    url: 'http://codepen.io/dmsanchez86/full/xVXjYW',
    preview: true,
    code: true,
    key: 'quotes',
  },
  {
    name: 'Ball Loader',
    url: 'http://codepen.io/dmsanchez86/full/OXjROz',
    preview: true,
    code: true,
    key: 'ball',
  },
  {
    name: 'Weather App',
    url: 'http://codepen.io/dmsanchez86/full/bpYXPN/',
    preview: true,
    code: true,
    key: 'weather',
  },
  {
    name: 'Perspective Slide',
    url: 'Perspective_Slider',
    preview: true,
    code: true,
    download: true,
    key: 'slide',
  },
  {
    name: 'Interactive Clock',
    url: 'interactive_clock',
    preview: true,
    code: true,
    download: true,
    key: 'clocl',
  },
  {
    name: 'Cellphone 3D',
    url: 'cellphone-3d',
    preview: true,
    code: true,
    download: true,
    key: 'cellphone',
  },
  {
    name: 'Cube 3D',
    url: 'Cube-3D---CSS3-and-JavaScript',
    preview: true,
    code: true,
    download: true,
    key: 'cube',
  },
  {
    name: 'Lists in 3D',
    url: 'list_in_3d',
    preview: true,
    code: true,
    download: true,
    key: 'lists',
  },
  {
    name: 'Geometry Cube 3D',
    url: 'cube_3D',
    preview: true,
    code: true,
    download: true,
    key: 'geometry_cube',
  },
  {
    name: 'Juris Quiz Web',
    url: 'jurisquizWeb',
    preview: true,
    code: true,
    download: true,
    key: 'jurisquiz_web',
  },
  {
    name: 'Arthritis Web',
    url: 'ArthritisWeb',
    preview: true,
    code: true,
    download: true,
    key: 'arthritis',
  },
  {
    name: 'Basic Angular Template',
    url: 'siema',
    preview: true,
    code: true,
    download: true,
    key: 'angular_template',
  },
  {
    name: 'Mecaut',
    url: 'https://github.com/dmsanchez86/Mecaut',
    preview: false,
    code: true,
    download: true,
    key: 'mecaut',
  },
];
